### ISSUE TITLE
x is not numeric error when export pathway with no events

### ISSUE THREAD

**Issue by rossdwilliams** [darwin-eu-dev/TreatmentPatterns#179] opened 2023-11-08 15:48 UTC
**Describe the bug**
When trying to export the output of a computePathways() analysis where no event occurs, the export function throws the following error

```R
Writing treatmentPathways to D:/Users/rwilliams/git/P2-C1-008-DUS-MDD/Results_ipci/anyAD_MDD_RW 4 weeks/mdd_diag_tp/treatmentPathways.csv
Error in `dplyr::mutate()`:
ℹ In argument: `ageBin = paste(...)`.
Caused by error in `cut.default()`:
! 'x' must be numeric
```

**To Reproduce**
[reprex_pathway.zip](https://github.com/darwin-eu-dev/TreatmentPatterns/files/13298659/reprex_pathway.zip)
```R
pathwaysObject <- Andromeda::loadAndromeda("reprex_pathway.zip")

export(
  andromeda = pathwaysObject ,
  outputPath = "Results",
  ageWindow = c(12,150),
  minFreq = 5,
  archiveName = NULL
)
```
**Expected behavior**
currently it returns the above error,  it would be good to be able to save this to show that no one has an event

**Comment by mvankessel-EMC** [comment] 2023-11-09 08:27
Hi @rossdwilliams thanks for the report. The error is caused by the `treatmentHistory` table being empty, but the error it throws is really cryptic. This should be resolved in the next version. I reran your example in that new version in the reprex below.


``` r
pathwaysObject <- Andromeda::loadAndromeda("D:/Users/mvankessel/Downloads/reprex_pathway.zip")

TreatmentPatterns::export(
  andromeda = pathwaysObject,
  outputPath = "Results",
  ageWindow = c(12,150),
  minFreq = 5,
  archiveName = NULL
)
#> Treatment History table is empty. Nothing to export.

pathwaysObject$treatmentHistory
#> # Source:   table<treatmentHistory> [0 x 10]
#> # Database: sqlite 3.41.2 [C:\Users\mvankessel\AppData\Local\Temp\RtmporUE1H\file476443c7719c.sqlite]
#> # ℹ 10 variables: personId <lgl>, indexYear <dbl>, eventCohortId <chr>,
#> #   eventStartDate <dbl>, eventEndDate <dbl>, type <lgl>, durationEra <lgl>,
#> #   gapSame <lgl>, sex <chr>, age <lgl>
```

<sup>Created on 2023-11-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.3.1 (2023-06-16 ucrt)
#>  os       Windows 11 x64 (build 22621)
#>  system   x86_64, mingw32
#>  ui       RTerm
#>  language (EN)
#>  collate  Dutch_Netherlands.utf8
#>  ctype    Dutch_Netherlands.utf8
#>  tz       Europe/Amsterdam
#>  date     2023-11-09
#>  pandoc   3.1.1 @ C:/Program Files/RStudio/resources/app/bin/quarto/bin/tools/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  ! package           * version date (UTC) lib source
#>    Andromeda           0.6.3   2023-03-26 [1] CRAN (R 4.3.1)
#>    backports           1.4.1   2021-12-13 [1] CRAN (R 4.3.0)
#>    bit                 4.0.5   2022-11-15 [1] CRAN (R 4.3.1)
#>    bit64               4.0.5   2020-08-30 [1] CRAN (R 4.3.1)
#>    blob                1.2.4   2023-03-17 [1] CRAN (R 4.3.1)
#>    cachem              1.0.8   2023-05-01 [1] CRAN (R 4.3.1)
#>    checkmate           2.2.0   2023-04-27 [1] CRAN (R 4.3.1)
#>    cli                 3.6.1   2023-03-23 [1] CRAN (R 4.3.1)
#>    codetools           0.2-19  2023-02-01 [1] CRAN (R 4.3.1)
#>    DBI                 1.1.3   2022-06-18 [1] CRAN (R 4.3.1)
#>    dbplyr              2.3.3   2023-07-07 [1] CRAN (R 4.3.1)
#>    digest              0.6.33  2023-07-07 [1] CRAN (R 4.3.1)
#>    dplyr               1.1.2   2023-04-20 [1] CRAN (R 4.3.1)
#>    evaluate            0.21    2023-05-05 [1] CRAN (R 4.3.1)
#>    fansi               1.0.4   2023-01-22 [1] CRAN (R 4.3.1)
#>    fastmap             1.1.1   2023-02-24 [1] CRAN (R 4.3.1)
#>    fs                  1.6.3   2023-07-20 [1] CRAN (R 4.3.1)
#>    generics            0.1.3   2022-07-05 [1] CRAN (R 4.3.1)
#>    glue                1.6.2   2022-02-24 [1] CRAN (R 4.3.1)
#>    googleVis           0.7.1   2023-03-01 [1] CRAN (R 4.3.1)
#>    hms                 1.1.3   2023-03-21 [1] CRAN (R 4.3.1)
#>    htmltools           0.5.6   2023-08-10 [1] CRAN (R 4.3.1)
#>    htmlwidgets         1.6.2   2023-03-17 [1] CRAN (R 4.3.1)
#>    igraph              1.5.0   2023-06-16 [1] CRAN (R 4.3.1)
#>    jsonlite            1.8.7   2023-06-29 [1] CRAN (R 4.3.1)
#>    knitr               1.43    2023-05-25 [1] RSPM (R 4.3.0)
#>    lifecycle           1.0.3   2022-10-07 [1] CRAN (R 4.3.1)
#>    magrittr            2.0.3   2022-03-30 [1] CRAN (R 4.3.1)
#>    memoise             2.0.1   2021-11-26 [1] CRAN (R 4.3.1)
#>    networkD3           0.4     2017-03-18 [1] CRAN (R 4.3.1)
#>    pillar              1.9.0   2023-03-22 [1] CRAN (R 4.3.1)
#>    pkgconfig           2.0.3   2019-09-22 [1] CRAN (R 4.3.1)
#>    purrr               1.0.1   2023-01-10 [1] CRAN (R 4.3.1)
#>    R.cache             0.16.0  2022-07-21 [1] CRAN (R 4.3.1)
#>    R.methodsS3         1.8.2   2022-06-13 [1] CRAN (R 4.3.0)
#>    R.oo                1.25.0  2022-06-12 [1] CRAN (R 4.3.0)
#>    R.utils             2.12.2  2022-11-11 [1] CRAN (R 4.3.1)
#>    R6                  2.5.1   2021-08-19 [1] CRAN (R 4.3.1)
#>    reprex              2.0.2   2022-08-17 [1] CRAN (R 4.3.1)
#>  D rJava               1.0-6   2021-12-10 [1] CRAN (R 4.3.0)
#>    rjson               0.2.21  2022-01-09 [1] CRAN (R 4.3.0)
#>    rlang               1.1.1   2023-04-28 [1] CRAN (R 4.3.1)
#>    rmarkdown           2.24    2023-08-14 [1] CRAN (R 4.3.1)
#>    RSQLite             2.3.1   2023-04-03 [1] CRAN (R 4.3.1)
#>    rstudioapi          0.15.0  2023-07-07 [1] CRAN (R 4.3.1)
#>    sessioninfo         1.2.2   2021-12-06 [1] CRAN (R 4.3.1)
#>    stringi             1.7.12  2023-01-11 [1] CRAN (R 4.3.0)
#>    stringr             1.5.0   2022-12-02 [1] CRAN (R 4.3.1)
#>    styler              1.10.1  2023-06-05 [1] CRAN (R 4.3.1)
#>    sunburstR           2.1.8   2023-02-05 [1] CRAN (R 4.3.1)
#>    tibble              3.2.1   2023-03-20 [1] CRAN (R 4.3.1)
#>    tidyr               1.3.0   2023-01-24 [1] CRAN (R 4.3.1)
#>    tidyselect          1.2.0   2022-10-10 [1] CRAN (R 4.3.1)
#>    TreatmentPatterns   2.6.0   2023-11-07 [1] local
#>    utf8                1.2.3   2023-01-31 [1] CRAN (R 4.3.1)
#>    vctrs               0.6.3   2023-06-14 [1] CRAN (R 4.3.1)
#>    withr               2.5.0   2022-03-03 [1] CRAN (R 4.3.1)
#>    xfun                0.40    2023-08-09 [1] CRAN (R 4.3.1)
#>    yaml                2.3.7   2023-01-23 [1] CRAN (R 4.3.0)
#>    zip                 2.3.0   2023-04-17 [1] CRAN (R 4.3.1)
#> 
#>  [1] C:/R/R-4.3.1/library
#> 
#>  D ── DLL MD5 mismatch, broken installation.
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

**Closed** 2023-11-13 11:46 UTC
